# 📊 Chapter 01: NumPy Foundations with Multiple Real Datasets

## 🎯 Learning Objectives
By the end of this chapter, you will:
- ✅ Understand what NumPy is and why it's essential for data science
- ✅ Master array creation, indexing, and slicing techniques
- ✅ Apply NumPy operations on **3 different real datasets** for maximum practice
- ✅ Perform statistical analysis and linear algebra operations
- ✅ Optimize code using vectorization (50-100x faster!)

---

## 📁 Datasets Used (Multiple datasets for maximum practice!)

We'll practice **each concept** on **3 different real-world datasets**:

### 1️⃣ California Housing Dataset (20,640 samples)
**Purpose**: Predict house prices
- MedInc: Median income in block group
- HouseAge: Median house age
- AveRooms: Average rooms per household
- Target: Median house value

### 2️⃣ Iris Flower Dataset (150 samples)
**Purpose**: Classify flower species
- Sepal Length, Sepal Width
- Petal Length, Petal Width
- Target: Species (0=Setosa, 1=Versicolor, 2=Virginica)

### 3️⃣ Wine Quality Dataset (178 samples)
**Purpose**: Classify wine types
- Alcohol, Malic Acid, Ash, Alkalinity
- Magnesium, Phenols, Flavanoids, etc.
- Target: Wine class (0, 1, 2)

**Why 3 datasets?** Practice makes perfect! Applying each concept to different datasets helps you understand deeply.

---

## 📚 Table of Contents
1. [Introduction to NumPy](#intro)
2. [**NumPy Basics - Essential Concepts (LEARN FIRST!)**](#basics)
3. [Loading Multiple Datasets](#loading)
4. [Array Creation Methods](#creation)
5. [Array Attributes & Data Types](#attributes)
6. [Indexing & Slicing](#indexing)
7. [Array Operations & Broadcasting](#operations)
8. [Statistical Operations](#statistics)
9. [Array Manipulation](#manipulation)
10. [Linear Algebra](#linear-algebra)
11. [Performance & Vectorization](#performance)
12. [Practice Exercises](#exercises)
13. [Next Steps: Projects](#projects)

**💡 Tip for Beginners:** Section 2 teaches you .shape, indexing, .dtype, and other basics BEFORE we use them. Don't skip it!

---
<a id="intro"></a>
## 1️⃣ Introduction to NumPy

### 📖 What is NumPy? (Detailed Explanation)

**NumPy** stands for **Numerical Python**. It is the most important library for scientific computing in Python.

#### Why NumPy Exists:
Python lists are flexible but **slow** for numerical operations because:
- Python lists store **references** to objects scattered in memory
- Python loops are **interpreted** (slow) not compiled (fast)
- Each element can be a different type, so Python checks types repeatedly

NumPy solves these problems by:
- Storing data in **contiguous memory** (all together, fast access)
- Using **pre-compiled C code** (50-100x faster)
- Enforcing **single data type** per array (no type checking overhead)
- Providing **vectorized operations** (no Python loops needed)

#### What NumPy Provides:
1. **ndarray**: N-dimensional array object (1D, 2D, 3D, etc.)
2. **Fast operations**: Addition, multiplication, etc. on entire arrays at once
3. **Mathematical functions**: sqrt, exp, log, sin, cos, etc.
4. **Linear algebra tools**: Matrix multiplication, inverse, eigenvalues
5. **Random number generation**: For simulations and testing
6. **Broadcasting**: Operations on arrays of different shapes

#### Real-World Use Cases:
- **Data Science**: Loading and processing large datasets efficiently
- **Machine Learning**: Neural network operations (all matrix math)
- **Finance**: Time-series analysis, portfolio optimization
- **Image Processing**: Each image is a 2D/3D NumPy array
- **Scientific Computing**: Physics simulations, engineering calculations

### 🔑 Key Concept: Arrays vs Lists

| Feature | Python List | NumPy Array |
|---------|-------------|-------------|
| **Speed** | Slow (interpreted) | Fast (compiled C) |
| **Memory** | More (scattered) | Less (contiguous) |
| **Data Types** | Mixed types allowed | Single type only |
| **Operations** | Limited | Rich math operations |
| **Size** | Dynamic (can grow) | Fixed at creation |
| **Dimensions** | 1D only (nested for 2D) | True multi-dimensional |

**Bottom Line**: Use Python lists for small collections of mixed data. Use NumPy arrays for numerical data and calculations.

---

<a id="basics"></a>
## 1.5️⃣ NumPy Basics - Essential Concepts (Learn These FIRST!)

### 📖 Before We Start: Fundamental Concepts

Before loading datasets, you MUST understand these core NumPy concepts. We'll use them constantly!

---

### 🔑 **Concept 1: Array Shape**

**What is Shape?**
- Shape tells you the **dimensions** of an array
- Think of it as the "size" of the array in each direction
- Accessed using `.shape` attribute

**Examples:**
- **1D array** (like a list): `shape = (5,)` → 5 elements in a row
- **2D array** (like a table): `shape = (3, 4)` → 3 rows, 4 columns
- **3D array** (like a cube): `shape = (2, 3, 4)` → 2 layers, 3 rows, 4 columns per layer

**How to Read Shape:**
```python
arr.shape = (20640, 8)
             ↑      ↑
           rows  columns
         samples features
```

---

### 🔑 **Concept 2: Indexing (Accessing Elements)**

**What is Indexing?**
- Accessing specific elements using **square brackets `[]`**
- Python uses **0-based indexing** (first element is index 0, not 1!)

**1D Array Indexing:**
```python
arr = [10, 20, 30, 40, 50]
arr[0]  → 10  (first element)
arr[1]  → 20  (second element)
arr[-1] → 50  (last element)
arr[-2] → 40  (second to last)
```

**2D Array Indexing:**
```python
arr = [[10, 20, 30],
       [40, 50, 60]]

arr[0, 0]  → 10  (row 0, column 0)
arr[0, 1]  → 20  (row 0, column 1)
arr[1, 2]  → 60  (row 1, column 2)
```

**Key Point:** `arr[row, column]` - comma separates dimensions!

---

### 🔑 **Concept 3: Data Types (dtype)**

**What is dtype?**
- Data type = what KIND of numbers the array stores
- All elements in a NumPy array must have the SAME type
- Accessed using `.dtype` attribute

**Common Data Types:**

| dtype | Meaning | Example | Memory |
|-------|---------|---------|--------|
| `int32` | 32-bit integer | -2147483648 to 2147483647 | 4 bytes |
| `int64` | 64-bit integer | Very large integers | 8 bytes |
| `float32` | 32-bit decimal | 3.14159 (7 digits precision) | 4 bytes |
| `float64` | 64-bit decimal | 3.14159265359 (15 digits) | 8 bytes |
| `bool` | Boolean | True or False | 1 byte |
| `object` | Python object | Any Python type (slow!) | varies |

**Default Types:**
- Integers → `int64`
- Decimals → `float64`
- Can specify: `np.array([1, 2, 3], dtype=np.float32)`

---

### 🔑 **Concept 4: Memory & Size**

**Understanding Memory:**
- **Byte** = basic unit of memory (can store 1 character)
- **1 KB** (Kilobyte) = 1,024 bytes
- **1 MB** (Megabyte) = 1,024 KB = 1,048,576 bytes
- **1 GB** (Gigabyte) = 1,024 MB

**NumPy Memory Attributes:**
- `.nbytes` = total bytes used by array
- `.itemsize` = bytes per element
- `.size` = total number of elements

**Calculation:**
```python
arr.shape = (1000, 10)  # 1000 rows, 10 columns
arr.dtype = float64     # 8 bytes per number
Total memory = 1000 × 10 × 8 = 80,000 bytes = 78.1 KB
```

---

### 🔑 **Concept 5: Array Dimensions**

**What are Dimensions?**
- **1D** (Vector): Single row of numbers `[1, 2, 3, 4, 5]`
- **2D** (Matrix): Table with rows and columns (most common in data science)
- **3D** (Tensor): Cube of data (e.g., video frames, RGB images)
- **4D+**: Multiple cubes (e.g., batch of RGB images)

**Shape Notation:**
- `(n,)` → 1D array with n elements (note the comma!)
- `(n, m)` → 2D array with n rows, m columns
- `(n, m, k)` → 3D array with n layers, m rows, k columns

**Why the comma in `(5,)`?**
- Python tuple notation: `(5)` is just number 5
- `(5,)` is a tuple with one element → tells us it's 1D

---

### 🔑 **Concept 6: Array Attributes & Methods**

**Attributes** (properties you can read):
- `.shape` → dimensions (rows, columns)
- `.dtype` → data type (int64, float32, etc.)
- `.ndim` → number of dimensions (1, 2, 3, ...)
- `.size` → total number of elements
- `.nbytes` → total memory used

**Methods** (functions you can call):
- `.mean()` → average of all elements
- `.sum()` → sum of all elements
- `.min()` → minimum value
- `.max()` → maximum value
- `.std()` → standard deviation
- `.reshape()` → change shape without changing data

---

### 🔑 **Concept 7: Slicing (Getting Multiple Elements)**

**What is Slicing?**
- Get a "slice" (portion) of an array
- Syntax: `arr[start:stop:step]`

**Examples:**
```python
arr = [0, 10, 20, 30, 40, 50, 60, 70, 80, 90]

arr[0:3]   → [0, 10, 20]     (elements 0, 1, 2)
arr[2:5]   → [20, 30, 40]    (elements 2, 3, 4)
arr[:3]    → [0, 10, 20]     (start from beginning)
arr[7:]    → [70, 80, 90]    (go to end)
arr[::2]   → [0, 20, 40, 60, 80]  (every 2nd element)
arr[::-1]  → [90, 80, 70, ...0]   (reverse)
```

**2D Slicing:**
```python
arr[0:2, 1:3]  → rows 0-1, columns 1-2
arr[:, 0]      → all rows, column 0
arr[0, :]      → row 0, all columns
```

---

### 🎯 **Quick Reference Summary**

```python
# Create array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Check properties
arr.shape      # (2, 3) - 2 rows, 3 columns
arr.dtype      # dtype('int64') - 64-bit integers
arr.ndim       # 2 - two dimensions
arr.size       # 6 - total elements
arr.nbytes     # 48 - bytes used (6 elements × 8 bytes each)

# Access elements
arr[0, 0]      # 1 - first row, first column
arr[1, 2]      # 6 - second row, third column
arr[0, :]      # [1, 2, 3] - first row, all columns
arr[:, 1]      # [2, 5] - all rows, second column

# Statistics
arr.mean()     # 3.5 - average
arr.sum()      # 21 - total sum
arr.min()      # 1 - minimum
arr.max()      # 6 - maximum
```

---

✅ **Now you understand the basics! Let's apply these concepts to real datasets...**

In [19]:
print("=" * 70)
print("HANDS-ON PRACTICE: ESSENTIAL NUMPY CONCEPTS")
print("=" * 70)

# ============================================================================
# PRACTICE 1: Understanding .shape
# ============================================================================
print("\n1️⃣ UNDERSTANDING .shape ATTRIBUTE")
print("-" * 70)

# Create different shaped arrays
arr_1d = np.array([10, 20, 30, 40, 50])
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])
arr_3d = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]]])

print("1D Array:")
print(arr_1d)
print(f"  Shape: {arr_1d.shape} → {arr_1d.shape[0]} elements")
print(f"  Note: (5,) has a comma! This means 1D array with 5 elements")

print("\n2D Array (like a table):")
print(arr_2d)
print(f"  Shape: {arr_2d.shape} → {arr_2d.shape[0]} rows × {arr_2d.shape[1]} columns")
print(f"  Reading: arr_2d.shape[0] = number of rows = {arr_2d.shape[0]}")
print(f"           arr_2d.shape[1] = number of columns = {arr_2d.shape[1]}")

print("\n3D Array (like stacked tables):")
print(arr_3d)
print(f"  Shape: {arr_3d.shape}")
print(f"  Reading: {arr_3d.shape[0]} layers, {arr_3d.shape[1]} rows, {arr_3d.shape[2]} columns per layer")

# ============================================================================
# PRACTICE 2: Indexing (Accessing Elements)
# ============================================================================
print("\n\n2️⃣ INDEXING - ACCESSING SPECIFIC ELEMENTS")
print("-" * 70)

# 1D indexing
print("1D Array indexing:")
print(f"  arr_1d = {arr_1d}")
print(f"  arr_1d[0] = {arr_1d[0]} (first element, index 0)")
print(f"  arr_1d[2] = {arr_1d[2]} (third element, index 2)")
print(f"  arr_1d[-1] = {arr_1d[-1]} (last element, negative index)")
print(f"  arr_1d[-2] = {arr_1d[-2]} (second to last)")

# 2D indexing
print("\n2D Array indexing:")
print(f"  arr_2d =")
print(arr_2d)
print(f"  arr_2d[0, 0] = {arr_2d[0, 0]} (row 0, column 0 - top-left)")
print(f"  arr_2d[0, 3] = {arr_2d[0, 3]} (row 0, column 3 - top-right)")
print(f"  arr_2d[2, 1] = {arr_2d[2, 1]} (row 2, column 1 - bottom area)")
print(f"  arr_2d[1, 2] = {arr_2d[1, 2]} (row 1, column 2 - middle)")
print(f"  Remember: arr_2d[row, column] ← comma separates dimensions!")

# ============================================================================
# PRACTICE 3: Data Types (dtype)
# ============================================================================
print("\n\n3️⃣ DATA TYPES (.dtype ATTRIBUTE)")
print("-" * 70)

# Different data types
int_array = np.array([1, 2, 3, 4, 5])
float_array = np.array([1.1, 2.2, 3.3])
bool_array = np.array([True, False, True])

# Explicit type specification
int32_array = np.array([1, 2, 3], dtype=np.int32)
float32_array = np.array([1.0, 2.0], dtype=np.float32)

print(f"Integer array: {int_array}")
print(f"  dtype: {int_array.dtype} (default for integers)")

print(f"\nFloat array: {float_array}")
print(f"  dtype: {float_array.dtype} (default for decimals)")

print(f"\nBoolean array: {bool_array}")
print(f"  dtype: {bool_array.dtype} (True/False values)")

print(f"\nExplicit int32: {int32_array}")
print(f"  dtype: {int32_array.dtype} (we specified 32-bit)")

print(f"\nExplicit float32: {float32_array}")
print(f"  dtype: {float32_array.dtype} (we specified 32-bit)")

# ============================================================================
# PRACTICE 4: Memory & Size
# ============================================================================
print("\n\n4️⃣ MEMORY & SIZE")
print("-" * 70)

# Create arrays of different sizes
small_array = np.array([1, 2, 3, 4, 5])  # 5 elements
medium_array = np.ones((100, 10))  # 100 rows × 10 columns = 1000 elements
large_array = np.zeros((1000, 100))  # 1000 rows × 100 columns = 100,000 elements

print("Small array (5 elements):")
print(f"  Shape: {small_array.shape}")
print(f"  Size (total elements): {small_array.size}")
print(f"  Dtype: {small_array.dtype}")
print(f"  Itemsize (bytes per element): {small_array.itemsize}")
print(f"  Total memory (.nbytes): {small_array.nbytes} bytes")
print(f"  Calculation: {small_array.size} elements × {small_array.itemsize} bytes = {small_array.nbytes} bytes")

print("\nMedium array (1,000 elements):")
print(f"  Shape: {medium_array.shape}")
print(f"  Size: {medium_array.size} elements")
print(f"  Memory: {medium_array.nbytes} bytes = {medium_array.nbytes / 1024:.2f} KB")

print("\nLarge array (100,000 elements):")
print(f"  Shape: {large_array.shape}")
print(f"  Size: {large_array.size:,} elements")
print(f"  Memory: {large_array.nbytes:,} bytes = {large_array.nbytes / 1024:.2f} KB = {large_array.nbytes / (1024**2):.2f} MB")
print(f"  Conversion: bytes → KB (÷1024) → MB (÷1024 again)")

# ============================================================================
# PRACTICE 5: Array Attributes
# ============================================================================
print("\n\n5️⃣ ALL ARRAY ATTRIBUTES AT A GLANCE")
print("-" * 70)

demo_array = np.array([[10, 20, 30, 40],
                       [50, 60, 70, 80],
                       [90, 100, 110, 120]])

print("Demo array:")
print(demo_array)
print(f"\nAll attributes:")
print(f"  .shape   = {demo_array.shape} (3 rows, 4 columns)")
print(f"  .ndim    = {demo_array.ndim} (number of dimensions)")
print(f"  .size    = {demo_array.size} (total elements)")
print(f"  .dtype   = {demo_array.dtype} (data type)")
print(f"  .itemsize = {demo_array.itemsize} bytes per element")
print(f"  .nbytes  = {demo_array.nbytes} bytes total")

# ============================================================================
# PRACTICE 6: Basic Methods (Statistics)
# ============================================================================
print("\n\n6️⃣ BASIC STATISTICAL METHODS")
print("-" * 70)

data = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print(f"Data: {data}")
print(f"\nStatistical methods:")
print(f"  .mean()   = {data.mean()} (average)")
print(f"  .sum()    = {data.sum()} (total sum)")
print(f"  .min()    = {data.min()} (minimum value)")
print(f"  .max()    = {data.max()} (maximum value)")
print(f"  .std()    = {data.std():.2f} (standard deviation)")
print(f"  .var()    = {data.var():.2f} (variance)")

# Methods on 2D arrays
data_2d = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

print(f"\n2D Data:")
print(data_2d)
print(f"\nStatistics on entire array:")
print(f"  Overall mean: {data_2d.mean()}")
print(f"  Overall sum: {data_2d.sum()}")

print(f"\nStatistics along axis 0 (down columns):")
print(f"  Column means: {data_2d.mean(axis=0)}")  # Average of each column

print(f"\nStatistics along axis 1 (across rows):")
print(f"  Row means: {data_2d.mean(axis=1)}")  # Average of each row

# ============================================================================
# PRACTICE 7: Slicing Basics
# ============================================================================
print("\n\n7️⃣ SLICING - GETTING MULTIPLE ELEMENTS")
print("-" * 70)

numbers = np.array([0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

print(f"Array: {numbers}")
print(f"\nBasic slicing (start:stop):")
print(f"  numbers[0:3]  = {numbers[0:3]} (indices 0, 1, 2)")
print(f"  numbers[2:5]  = {numbers[2:5]} (indices 2, 3, 4)")
print(f"  numbers[5:8]  = {numbers[5:8]} (indices 5, 6, 7)")

print(f"\nShorthand slicing:")
print(f"  numbers[:3]   = {numbers[:3]} (start from beginning)")
print(f"  numbers[7:]   = {numbers[7:]} (go to end)")
print(f"  numbers[:]    = {numbers[:]} (entire array)")

print(f"\nStep slicing (start:stop:step):")
print(f"  numbers[::2]  = {numbers[::2]} (every 2nd element)")
print(f"  numbers[::3]  = {numbers[::3]} (every 3rd element)")
print(f"  numbers[::-1] = {numbers[::-1]} (reverse array)")

# 2D slicing
grid = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])

print(f"\n2D Array:")
print(grid)
print(f"\n2D Slicing:")
print(f"  grid[0:2, 1:3] = get rows 0-1, columns 1-2:")
print(grid[0:2, 1:3])
print(f"\n  grid[:, 0] = all rows, column 0: {grid[:, 0]}")
print(f"  grid[1, :] = row 1, all columns: {grid[1, :]}")
print(f"  grid[:2, :2] = top-left 2×2:")
print(grid[:2, :2])

print("\n" + "=" * 70)
print("✅ ESSENTIAL CONCEPTS MASTERED!")
print("Now you understand: .shape, indexing, .dtype, memory, methods, slicing")
print("=" * 70)

HANDS-ON PRACTICE: ESSENTIAL NUMPY CONCEPTS

1️⃣ UNDERSTANDING .shape ATTRIBUTE
----------------------------------------------------------------------
1D Array:
[10 20 30 40 50]
  Shape: (5,) → 5 elements
  Note: (5,) has a comma! This means 1D array with 5 elements

2D Array (like a table):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
  Shape: (3, 4) → 3 rows × 4 columns
  Reading: arr_2d.shape[0] = number of rows = 3
           arr_2d.shape[1] = number of columns = 4

3D Array (like stacked tables):
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
  Shape: (2, 2, 2)
  Reading: 2 layers, 2 rows, 2 columns per layer


2️⃣ INDEXING - ACCESSING SPECIFIC ELEMENTS
----------------------------------------------------------------------
1D Array indexing:
  arr_1d = [10 20 30 40 50]
  arr_1d[0] = 10 (first element, index 0)
  arr_1d[2] = 30 (third element, index 2)
  arr_1d[-1] = 50 (last element, negative index)
  arr_1d[-2] = 40 (second to last)

2D Array indexing:
  arr_2d =
[[ 1  2  3  4]
 [ 5  6  7 

In [20]:
# Import NumPy library
# NumPy is imported with alias 'np' (standard convention in data science community)
import numpy as np

# Check which version of NumPy is installed
# This helps ensure compatibility (we need NumPy 1.20+)
print(f"NumPy version: {np.__version__}")

# Quick demo: Why NumPy is important
# Let's compare a Python list vs NumPy array
python_list = [1, 2, 3, 4, 5]  # Traditional Python list
numpy_array = np.array([1, 2, 3, 4, 5])  # NumPy array

print(f"\nPython list: {python_list}")
print(f"Type: {type(python_list)}")

print(f"\nNumPy array: {numpy_array}")
print(f"Type: {type(numpy_array)}")

# Try to multiply each element by 2
# With Python list: Need a loop or list comprehension
python_result = [x * 2 for x in python_list]  # Slow, needs loop
print(f"\nPython list * 2: {python_result}")

# With NumPy: Direct vectorized operation (MUCH faster!)
numpy_result = numpy_array * 2  # Fast, no loop needed!
print(f"NumPy array * 2: {numpy_result}")

print("\n✅ NumPy operations are vectorized = NO LOOPS = FAST!")

NumPy version: 2.3.1

Python list: [1, 2, 3, 4, 5]
Type: <class 'list'>

NumPy array: [1 2 3 4 5]
Type: <class 'numpy.ndarray'>

Python list * 2: [2, 4, 6, 8, 10]
NumPy array * 2: [ 2  4  6  8 10]

✅ NumPy operations are vectorized = NO LOOPS = FAST!


---
<a id="loading"></a>
## 2️⃣ Loading Multiple Real Datasets

### 📖 Concept: Loading Data into NumPy Arrays

In real-world projects, data comes from various sources:
- **CSV files**: Most common (comma-separated values)
- **Databases**: SQL queries → NumPy arrays
- **APIs**: JSON data → NumPy arrays
- **Built-in datasets**: sklearn, seaborn libraries
- **Excel files**: pandas → NumPy arrays

**For this tutorial**: We'll use sklearn's built-in datasets (already cleaned and ready to use).

### Why Multiple Datasets?
Practicing on **different datasets** helps you:
1. **Generalize knowledge**: Don't memorize one dataset
2. **See patterns**: Understand concepts work everywhere
3. **Build confidence**: More practice = deeper understanding
4. **Real-world ready**: Real projects have varied data

Let's load all 3 datasets and explore them!

In [21]:
# Import sklearn library to load built-in datasets
# sklearn (scikit-learn) is a machine learning library that includes sample datasets
from sklearn.datasets import fetch_california_housing, load_iris, load_wine

print("=" * 70)
print("LOADING 3 REAL-WORLD DATASETS")
print("=" * 70)

# ============================================================================
# DATASET 1: CALIFORNIA HOUSING PRICES
# ============================================================================
# fetch_california_housing() downloads housing data from California (1990 census)
# This is a REGRESSION problem (predict continuous values: house prices)
housing = fetch_california_housing()

# Extract features (X) and target (y) as NumPy arrays
X_housing = housing.data  # Features: Income, House Age, Rooms, etc.
y_housing = housing.target  # Target: Median house price ($100,000s)
housing_features = housing.feature_names  # Names of features

print("\n📊 DATASET 1: California Housing Prices")
print("-" * 70)
print(f"Purpose: Predict house prices (Regression)")
print(f"Shape: {X_housing.shape}")  # (rows, columns) = (samples, features)
print(f"  → {X_housing.shape[0]:,} houses")  # Number of samples
print(f"  → {X_housing.shape[1]} features")  # Number of features per house
print(f"Features: {housing_features}")
print(f"Target: House prices (min=${y_housing.min():.1f}, max=${y_housing.max():.1f} in $100K)")
print(f"Data type: {X_housing.dtype}")  # float64 = 64-bit floating point numbers
print(f"Memory: {X_housing.nbytes / (1024**2):.2f} MB")  # Convert bytes to megabytes

# ============================================================================
# DATASET 2: IRIS FLOWERS
# ============================================================================
# load_iris() loads famous Iris flower dataset (Fisher, 1936)
# This is a CLASSIFICATION problem (predict categories: flower species)
iris = load_iris()

# Extract features (X) and target (y) as NumPy arrays
X_iris = iris.data  # Features: Sepal/Petal measurements in cm
y_iris = iris.target  # Target: Species (0, 1, 2)
iris_features = iris.feature_names  # Names of features
iris_targets = iris.target_names  # Names of species

print("\n🌸 DATASET 2: Iris Flowers")
print("-" * 70)
print(f"Purpose: Classify flower species (Classification)")
print(f"Shape: {X_iris.shape}")
print(f"  → {X_iris.shape[0]} flowers")
print(f"  → {X_iris.shape[1]} measurements per flower")
print(f"Features: {iris_features}")
print(f"Target: Species {iris_targets}")
print(f"  → 0={iris_targets[0]}, 1={iris_targets[1]}, 2={iris_targets[2]}")
print(f"Data type: {X_iris.dtype}")
print(f"Memory: {X_iris.nbytes / 1024:.2f} KB")  # Small dataset, in kilobytes

# ============================================================================
# DATASET 3: WINE QUALITY
# ============================================================================
# load_wine() loads wine dataset with chemical analysis
# This is a CLASSIFICATION problem (predict categories: wine type)
wine = load_wine()

# Extract features (X) and target (y) as NumPy arrays
X_wine = wine.data  # Features: Alcohol, Acidity, Phenols, etc.
y_wine = wine.target  # Target: Wine class (0, 1, 2)
wine_features = wine.feature_names  # Names of features
wine_targets = wine.target_names  # Names of wine classes

print("\n🍷 DATASET 3: Wine Quality")
print("-" * 70)
print(f"Purpose: Classify wine types (Classification)")
print(f"Shape: {X_wine.shape}")
print(f"  → {X_wine.shape[0]} wine samples")
print(f"  → {X_wine.shape[1]} chemical measurements per sample")
print(f"Features: {wine_features[:3]} ... (showing first 3 of {len(wine_features)})")
print(f"Target: Wine classes {wine_targets}")
print(f"Data type: {X_wine.dtype}")
print(f"Memory: {X_wine.nbytes / 1024:.2f} KB")

print("\n" + "=" * 70)
print("✅ ALL 3 DATASETS LOADED SUCCESSFULLY!")
print("=" * 70)

# Quick summary comparison
print("\n📊 QUICK COMPARISON:")
print(f"{'Dataset':<20} {'Samples':<10} {'Features':<10} {'Type':<15}")
print("-" * 70)
print(f"{'California Housing':<20} {X_housing.shape[0]:<10} {X_housing.shape[1]:<10} {'Regression':<15}")
print(f"{'Iris Flowers':<20} {X_iris.shape[0]:<10} {X_iris.shape[1]:<10} {'Classification':<15}")
print(f"{'Wine Quality':<20} {X_wine.shape[0]:<10} {X_wine.shape[1]:<10} {'Classification':<15}")

LOADING 3 REAL-WORLD DATASETS

📊 DATASET 1: California Housing Prices
----------------------------------------------------------------------
Purpose: Predict house prices (Regression)
Shape: (20640, 8)
  → 20,640 houses
  → 8 features
Features: ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude']
Target: House prices (min=$0.1, max=$5.0 in $100K)
Data type: float64
Memory: 1.26 MB

🌸 DATASET 2: Iris Flowers
----------------------------------------------------------------------
Purpose: Classify flower species (Classification)
Shape: (150, 4)
  → 150 flowers
  → 4 measurements per flower
Features: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target: Species ['setosa' 'versicolor' 'virginica']
  → 0=setosa, 1=versicolor, 2=virginica
Data type: float64
Memory: 4.69 KB

🍷 DATASET 3: Wine Quality
----------------------------------------------------------------------
Purpose: Classify wine types (Classificati

---
<a id="creation"></a>
## 3️⃣ Array Creation Methods

### 📖 Concept: How to Create NumPy Arrays

NumPy arrays are the foundation of numerical computing in Python. Unlike Python lists, NumPy arrays:
- Must have a **fixed size** at creation
- Must contain **same data type** for all elements
- Are stored in **contiguous memory** (all data together, not scattered)

### 🎯 Common Creation Methods:

1. **`np.array(list)`** - Convert Python list to NumPy array
2. **`np.zeros(shape)`** - Create array filled with zeros
3. **`np.ones(shape)`** - Create array filled with ones
4. **`np.full(shape, value)`** - Create array filled with a specific value
5. **`np.arange(start, stop, step)`** - Create array with range of values
6. **`np.linspace(start, stop, num)`** - Create array with evenly spaced values
7. **`np.eye(n)`** - Create identity matrix (1s on diagonal, 0s elsewhere)
8. **`np.random.rand()`** - Create array with random values [0, 1)
9. **`np.random.randn()`** - Create array with random values from normal distribution
10. **`np.empty(shape)`** - Create uninitialized array (fastest, but contains garbage)

### 🔑 Key Points:
- **Shape** = dimensions of array, e.g., (3, 4) means 3 rows × 4 columns
- **dtype** = data type (int32, float64, bool, etc.)
- NumPy automatically infers dtype, but you can specify it

Let's practice each method with examples from our 3 datasets!

In [22]:
print("=" * 70)
print("ARRAY CREATION METHODS - PRACTICE ON 3 DATASETS")
print("=" * 70)

# ============================================================================
# METHOD 1: np.array() - Convert Python list to NumPy array
# ============================================================================
print("\n1️⃣ CREATE FROM LIST: np.array()")
print("-" * 70)

# Example 1: Create array from housing prices (first 5 samples)
# We extract first 5 prices and convert to array
housing_prices_list = [y_housing[0], y_housing[1], y_housing[2], y_housing[3], y_housing[4]]
housing_prices_array = np.array(housing_prices_list)  # Convert list → NumPy array
print(f"Housing prices (first 5): {housing_prices_array}")
print(f"  Type: {type(housing_prices_array)}")  # Shows this is np.ndarray
print(f"  Shape: {housing_prices_array.shape}")  # (5,) means 1D array with 5 elements
print(f"  Dtype: {housing_prices_array.dtype}")  # float64 = 64-bit decimal numbers

# Example 2: Create array from iris petal lengths (first 5 samples)
# Column index 2 = Petal Length (in cm)
iris_petal_lengths = np.array([X_iris[0, 2], X_iris[1, 2], X_iris[2, 2], X_iris[3, 2], X_iris[4, 2]])
print(f"\nIris petal lengths (first 5): {iris_petal_lengths} cm")
print(f"  Shape: {iris_petal_lengths.shape}")

# Example 3: Create 2D array from wine alcohol content (first 3 samples, first 2 features)
wine_sample = np.array([[X_wine[0, 0], X_wine[0, 1]],  # First wine: [Alcohol, Malic Acid]
                        [X_wine[1, 0], X_wine[1, 1]],  # Second wine
                        [X_wine[2, 0], X_wine[2, 1]]])  # Third wine
print(f"\nWine features (3 samples × 2 features):")
print(wine_sample)
print(f"  Shape: {wine_sample.shape}")  # (3, 2) = 3 rows, 2 columns = 2D array

# ============================================================================
# METHOD 2: np.zeros() - Array filled with zeros
# ============================================================================
print("\n\n2️⃣ CREATE ZEROS ARRAY: np.zeros()")
print("-" * 70)
print("Use case: Initialize predictions, create empty containers")

# Example 1: Create array to store housing price predictions (1D)
housing_predictions = np.zeros(5)  # 5 elements, all zeros
print(f"Housing predictions (initialized): {housing_predictions}")
print(f"  Shape: {housing_predictions.shape}")

# Example 2: Create 2D array for storing iris classification results
# 150 samples, 3 possible classes (one-hot encoding style)
iris_results = np.zeros((5, 3))  # 5 samples × 3 classes = 2D array
print(f"\nIris classification results (5 samples × 3 classes):")
print(iris_results)
print(f"  Shape: {iris_results.shape}")

# Example 3: Create 3D array for image-like data
# Simulating 10 images of 28×28 pixels
image_batch = np.zeros((10, 28, 28))  # 10 images, 28 rows, 28 columns each
print(f"\nImage batch: {image_batch.shape} (10 images of 28×28)")

# ============================================================================
# METHOD 3: np.ones() - Array filled with ones
# ============================================================================
print("\n\n3️⃣ CREATE ONES ARRAY: np.ones()")
print("-" * 70)
print("Use case: Bias terms in ML, default values, masks")

# Example 1: Create bias term for housing regression (intercept term)
# In linear regression: y = w₀×1 + w₁×x₁ + w₂×x₂ + ...
# The '1' is the bias term
bias_housing = np.ones(10)  # 10 samples, all ones
print(f"Bias term for housing (10 samples): {bias_housing}")

# Example 2: Create mask for valid iris samples
# 1 = valid sample, 0 = invalid (here all are valid)
iris_mask = np.ones(150, dtype=bool)  # dtype=bool converts 1→True, 0→False
print(f"\nIris valid samples mask (first 10): {iris_mask[:10]}")
print(f"  Total valid: {iris_mask.sum()}")  # sum() counts True values

# Example 3: Create weight matrix filled with ones
# Starting point before training in neural networks
weights = np.ones((3, 4))  # 3 inputs → 4 neurons
print(f"\nWeight matrix (3×4):")
print(weights)

# ============================================================================
# METHOD 4: np.full() - Array filled with custom value
# ============================================================================
print("\n\n4️⃣ CREATE CUSTOM VALUE ARRAY: np.full()")
print("-" * 70)
print("Use case: Initialize with specific value (e.g., mean, median)")

# Example 1: Fill with average housing price
avg_price = y_housing.mean()  # Calculate average price
baseline_predictions = np.full(5, avg_price)  # Create array filled with average
print(f"Average housing price: ${avg_price:.2f} (in $100K)")
print(f"Baseline predictions (all avg): {baseline_predictions}")

# Example 2: Fill with typical iris petal length
typical_petal = 3.758  # Average petal length in dataset
iris_defaults = np.full(10, typical_petal)
print(f"\nTypical iris petal length: {typical_petal} cm")
print(f"Default values: {iris_defaults}")

# Example 3: Fill with specific value (e.g., missing data indicator)
missing_indicator = -999  # Common way to mark missing data
wine_with_missing = np.full((3, 5), missing_indicator)  # 3 samples × 5 features
print(f"\nWine data with missing values marked as {missing_indicator}:")
print(wine_with_missing)

print("\n✅ Array creation methods demonstrated on all 3 datasets!")

ARRAY CREATION METHODS - PRACTICE ON 3 DATASETS

1️⃣ CREATE FROM LIST: np.array()
----------------------------------------------------------------------
Housing prices (first 5): [4.526 3.585 3.521 3.413 3.422]
  Type: <class 'numpy.ndarray'>
  Shape: (5,)
  Dtype: float64

Iris petal lengths (first 5): [1.4 1.4 1.3 1.5 1.4] cm
  Shape: (5,)

Wine features (3 samples × 2 features):
[[14.23  1.71]
 [13.2   1.78]
 [13.16  2.36]]
  Shape: (3, 2)


2️⃣ CREATE ZEROS ARRAY: np.zeros()
----------------------------------------------------------------------
Use case: Initialize predictions, create empty containers
Housing predictions (initialized): [0. 0. 0. 0. 0.]
  Shape: (5,)

Iris classification results (5 samples × 3 classes):
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
  Shape: (5, 3)

Image batch: (10, 28, 28) (10 images of 28×28)


3️⃣ CREATE ONES ARRAY: np.ones()
----------------------------------------------------------------------
Use case: Bias terms in ML, default 

In [23]:
# ============================================================================
# METHOD 5: np.arange() - Array with range of values (like Python range())
# ============================================================================
print("\n\n5️⃣ CREATE RANGE ARRAY: np.arange(start, stop, step)")
print("-" * 70)
print("Use case: Create indices, sequence numbers, loops replacement")

# Example 1: Create house IDs for first 20 houses
house_ids = np.arange(1, 21)  # Start=1, Stop=21 (exclusive), Step=1 (default)
print(f"House IDs (1-20): {house_ids}")

# Example 2: Create iris sample indices (0 to 149)
iris_indices = np.arange(0, 150)  # 0, 1, 2, ..., 149
print(f"\nIris indices (first 10): {iris_indices[:10]}")
print(f"  Total: {len(iris_indices)} indices")

# Example 3: Create every 5th wine sample (0, 5, 10, 15, ...)
wine_subset_ids = np.arange(0, 50, 5)  # Step=5, so skip 4 samples each time
print(f"\nWine samples (every 5th): {wine_subset_ids}")

# ============================================================================
# METHOD 6: np.linspace() - Array with evenly spaced values
# ============================================================================
print("\n\n6️⃣ CREATE EVENLY SPACED ARRAY: np.linspace(start, stop, num)")
print("-" * 70)
print("Use case: Create smooth ranges for plotting, interpolation")

# Example 1: Create 5 evenly spaced prices from min to max housing price
min_price = y_housing.min()
max_price = y_housing.max()
price_bins = np.linspace(min_price, max_price, 5)  # 5 values including start and stop
print(f"Housing price bins (min to max):")
print(f"  ${price_bins} (in $100K)")

# Example 2: Create 10 values between shortest and longest iris petal
min_petal = X_iris[:, 2].min()  # Column 2 = Petal Length
max_petal = X_iris[:, 2].max()
petal_range = np.linspace(min_petal, max_petal, 10)
print(f"\nIris petal length range ({min_petal:.1f}cm to {max_petal:.1f}cm):")
print(f"  {petal_range}")

# Example 3: Create smooth alcohol percentage range for wine
# Useful for plotting or creating test data
alcohol_range = np.linspace(11.0, 15.0, 20)  # 20 values from 11% to 15%
print(f"\nWine alcohol range (11% to 15%, 20 values):")
print(f"  {alcohol_range}")

# ============================================================================
# METHOD 7: np.eye() / np.identity() - Identity matrix (diagonal = 1, rest = 0)
# ============================================================================
print("\n\n7️⃣ CREATE IDENTITY MATRIX: np.eye(n)")
print("-" * 70)
print("Use case: Linear algebra, initialization, unit transformations")

# Example 1: 3×3 identity matrix for 3-feature housing data
identity_3x3 = np.eye(3)  # 3 rows × 3 columns
print(f"Identity matrix 3×3 (for 3 features):")
print(identity_3x3)

# Example 2: 4×4 identity for iris features (4 measurements)
identity_4x4 = np.identity(4)  # Same as np.eye(4)
print(f"\nIdentity matrix 4×4 (for 4 iris features):")
print(identity_4x4)

# ============================================================================
# METHOD 8 & 9: Random arrays
# ============================================================================
print("\n\n8️⃣ & 9️⃣ CREATE RANDOM ARRAYS")
print("-" * 70)
print("Use case: Simulations, testing, weight initialization")

# Set random seed for reproducibility (same \"random\" numbers every time)
np.random.seed(42)  # Magic number: Everyone uses 42 (from Hitchhiker's Guide!)

# Method 8: np.random.rand() - Uniform distribution [0, 1)
# Each value has equal probability between 0 and 1
random_uniform = np.random.rand(5)  # 5 random values
print(f"Random uniform [0, 1): {random_uniform}")

# Method 9: np.random.randn() - Normal distribution (mean=0, std=1)
# Bell curve: Most values near 0, few values far from 0
random_normal = np.random.randn(5)  # 5 random values from normal distribution
print(f"Random normal (μ=0, σ=1): {random_normal}")

# Example: Add random noise to housing prices (data augmentation)
sample_prices = y_housing[:5].copy()  # Copy first 5 prices
noise = np.random.randn(5) * 0.1  # Small random noise (std=0.1)
noisy_prices = sample_prices + noise  # Add noise to prices
print(f"\nOriginal housing prices: {sample_prices}")
print(f"Random noise added: {noise}")
print(f"Noisy prices: {noisy_prices}")

# Example: Generate random feature matrix for testing
# Simulating 10 samples with 4 features (like iris dataset)
random_features = np.random.randn(10, 4)  # 10 samples × 4 features
print(f"\nRandom feature matrix (10×4) for testing:")
print(random_features)
print(f"  Shape: {random_features.shape}")

print("\n" + "=" * 70)
print("✅ ALL ARRAY CREATION METHODS MASTERED!")
print("=" * 70)



5️⃣ CREATE RANGE ARRAY: np.arange(start, stop, step)
----------------------------------------------------------------------
Use case: Create indices, sequence numbers, loops replacement
House IDs (1-20): [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Iris indices (first 10): [0 1 2 3 4 5 6 7 8 9]
  Total: 150 indices

Wine samples (every 5th): [ 0  5 10 15 20 25 30 35 40 45]


6️⃣ CREATE EVENLY SPACED ARRAY: np.linspace(start, stop, num)
----------------------------------------------------------------------
Use case: Create smooth ranges for plotting, interpolation
Housing price bins (min to max):
  $[0.14999  1.362495 2.575    3.787505 5.00001 ] (in $100K)

Iris petal length range (1.0cm to 6.9cm):
  [1.         1.65555556 2.31111111 2.96666667 3.62222222 4.27777778
 4.93333333 5.58888889 6.24444444 6.9       ]

Wine alcohol range (11% to 15%, 20 values):
  [11.         11.21052632 11.42105263 11.63157895 11.84210526 12.05263158
 12.26315789 12.47368421 12.68421053 1

---
<a id="indexing"></a>
## 4️⃣ Indexing & Slicing - Accessing Array Elements

### 📖 Concept: How to Access Data in NumPy Arrays

**Indexing** = Accessing specific elements, rows, or columns
**Slicing** = Extracting a portion (subset) of an array

Think of arrays like a spreadsheet:
- **Index** = Cell address (row, column)
- **Slice** = Range of cells (rows 1-5, columns 2-4)

### 🎯 Indexing Rules:

#### 1D Arrays (like a single row):
```python
arr[i]           # Get element at position i
arr[-1]          # Last element (negative indexing from end)
arr[start:stop]  # Slice from start to stop-1
arr[start:stop:step]  # Slice with step size
```

#### 2D Arrays (like a table):
```python
arr[row, col]    # Get single element
arr[row, :]      # Get entire row (: means "all")
arr[:, col]      # Get entire column
arr[r1:r2, c1:c2]  # Get sub-matrix (rows r1 to r2-1, cols c1 to c2-1)
```

### 🔑 Key Points:
1. **Indexing starts at 0** (first element = 0, second = 1, ...)
2. **Negative indexing** from end (-1 = last, -2 = second-to-last)
3. **Slicing is INCLUSIVE of start, EXCLUSIVE of stop**
   - `arr[0:3]` gives elements 0, 1, 2 (NOT 3)
4. **Slicing creates VIEWS, not copies**
   - Changing sliced array changes original!
   - Use `.copy()` to create independent copy

### 📊 Types of Indexing:
1. **Basic indexing**: Using integers
2. **Slicing**: Using colon `:`
3. **Boolean indexing**: Using True/False masks
4. **Fancy indexing**: Using arrays of indices

Let's practice on all 3 datasets!

In [24]:
print("=" * 70)
print("INDEXING & SLICING - PRACTICE ON 3 DATASETS")
print("=" * 70)

# ============================================================================
# PART 1: BASIC INDEXING - Single Elements
# ============================================================================
print("\n1️⃣ BASIC INDEXING - Accessing Single Elements")
print("-" * 70)

# Dataset 1: Housing - Get specific house information
print("🏠 HOUSING DATASET:")
first_house = X_housing[0]  # Get all features of first house (index 0)
print(f"First house all features: {first_house}")
print(f"  Shape: {first_house.shape}")  # (8,) = 1D array with 8 elements

last_house = X_housing[-1]  # Negative index: -1 = last element
print(f"Last house all features: {last_house}")

# Get specific feature of specific house
first_house_income = X_housing[0, 0]  # Row 0, Column 0 = First house, Median Income
print(f"First house median income: {first_house_income}")

first_house_rooms = X_housing[0, 2]  # Row 0, Column 2 = Average Rooms
print(f"First house average rooms: {first_house_rooms}")

first_house_price = y_housing[0]  # Get first house price from target array
print(f"First house price: ${first_house_price:.2f} (in $100K) = ${first_house_price * 100000:,.0f}")

# Dataset 2: Iris - Get specific flower information
print("\n🌸 IRIS DATASET:")
first_flower = X_iris[0]  # Get all 4 measurements of first flower
print(f"First flower all measurements: {first_flower} cm")
print(f"  Features: {iris_features}")

# Get specific measurements
first_flower_sepal_length = X_iris[0, 0]  # Row 0, Col 0 = Sepal Length
first_flower_petal_width = X_iris[0, 3]  # Row 0, Col 3 = Petal Width
print(f"First flower sepal length: {first_flower_sepal_length} cm")
print(f"First flower petal width: {first_flower_petal_width} cm")

first_flower_species = y_iris[0]  # Get species (0, 1, or 2)
print(f"First flower species: {first_flower_species} ({iris_targets[first_flower_species]})")

# Dataset 3: Wine - Get specific wine sample
print("\n🍷 WINE DATASET:")
first_wine = X_wine[0]  # Get all chemical measurements of first wine
print(f"First wine measurements (first 5 of {len(first_wine)}): {first_wine[:5]}")

first_wine_alcohol = X_wine[0, 0]  # Alcohol content
first_wine_phenols = X_wine[0, 6]  # Total phenols (column 6)
print(f"First wine alcohol: {first_wine_alcohol}%")
print(f"First wine phenols: {first_wine_phenols}")

first_wine_class = y_wine[0]
print(f"First wine class: {first_wine_class} ({wine_targets[first_wine_class]})")

# ============================================================================
# PART 2: SLICING - Multiple Elements
# ============================================================================
print("\n\n2️⃣ SLICING - Extracting Subsets")
print("-" * 70)

# Dataset 1: Housing - Get first 5 houses
print("🏠 HOUSING DATASET:")
first_5_houses = X_housing[:5]  # Rows 0-4 (stop=5 is exclusive), all columns
print(f"First 5 houses shape: {first_5_houses.shape}")  # (5, 8) = 5 houses × 8 features
print(f"First 5 houses:\n{first_5_houses}")

# Get first 5 houses, but only first 3 features
first_5_houses_3_features = X_housing[:5, :3]  # Rows 0-4, Columns 0-2
print(f"\nFirst 5 houses, first 3 features (MedInc, HouseAge, AveRooms):")
print(first_5_houses_3_features)

# Get houses 10-15 (middle of dataset)
middle_houses = X_housing[10:15]  # Rows 10-14 (15 is exclusive)
print(f"\nHouses 10-15 shape: {middle_houses.shape}")

# Get last 3 houses
last_3_houses = X_housing[-3:]  # Last 3 rows (negative slicing)
print(f"Last 3 houses shape: {last_3_houses.shape}")

# Get every 10th house (step=10)
every_10th_house = X_housing[::10]  # Start=0 (default), stop=end (default), step=10
print(f"Every 10th house shape: {every_10th_house.shape}")  # 20640/10 ≈ 2064 houses

# Dataset 2: Iris - Get flowers by species
print("\n🌸 IRIS DATASET:")
# Iris dataset is organized: First 50 = Setosa, Next 50 = Versicolor, Last 50 = Virginica
setosa_flowers = X_iris[0:50]  # First 50 flowers (all Setosa)
versicolor_flowers = X_iris[50:100]  # Flowers 50-99 (all Versicolor)
virginica_flowers = X_iris[100:150]  # Flowers 100-149 (all Virginica)

print(f"Setosa flowers: {setosa_flowers.shape}")  # (50, 4)
print(f"Versicolor flowers: {versicolor_flowers.shape}")
print(f"Virginica flowers: {virginica_flowers.shape}")

# Get only petal measurements (columns 2 and 3)
petal_measurements = X_iris[:, 2:4]  # All rows, columns 2-3 (Petal Length & Width)
print(f"\nAll petal measurements shape: {petal_measurements.shape}")  # (150, 2)
print(f"First 3 flowers' petal measurements:\n{petal_measurements[:3]}")

# Dataset 3: Wine - Get subset of wines
print("\n🍷 WINE DATASET:")
first_10_wines = X_wine[:10]  # First 10 wine samples
print(f"First 10 wines shape: {first_10_wines.shape}")  # (10, 13)

# Get only first 3 chemical measurements for all wines
first_3_chemicals = X_wine[:, :3]  # All rows, columns 0-2
print(f"All wines, first 3 chemicals shape: {first_3_chemicals.shape}")  # (178, 3)
print(f"Features: {wine_features[:3]}")
print(f"First 3 wines, first 3 chemicals:\n{first_3_chemicals[:3]}")

print("\n✅ Basic indexing and slicing completed on all 3 datasets!")

INDEXING & SLICING - PRACTICE ON 3 DATASETS

1️⃣ BASIC INDEXING - Accessing Single Elements
----------------------------------------------------------------------
🏠 HOUSING DATASET:
First house all features: [   8.3252       41.            6.98412698    1.02380952  322.
    2.55555556   37.88       -122.23      ]
  Shape: (8,)
Last house all features: [ 2.38860000e+00  1.60000000e+01  5.25471698e+00  1.16226415e+00
  1.38700000e+03  2.61698113e+00  3.93700000e+01 -1.21240000e+02]
First house median income: 8.3252
First house average rooms: 6.984126984126984
First house price: $4.53 (in $100K) = $452,600

🌸 IRIS DATASET:
First flower all measurements: [5.1 3.5 1.4 0.2] cm
  Features: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
First flower sepal length: 5.1 cm
First flower petal width: 0.2 cm
First flower species: 0 (setosa)

🍷 WINE DATASET:
First wine measurements (first 5 of 13): [ 14.23   1.71   2.43  15.6  127.  ]
First wine alcohol: 14.23%
Fir

In [25]:
# ============================================================================
# PART 3: BOOLEAN INDEXING - Filter with Conditions
# ============================================================================
print("\n\n3️⃣ BOOLEAN INDEXING - Filtering with True/False Masks")
print("-" * 70)
print("Use case: Find data matching conditions (>, <, ==, etc.)")

# Dataset 1: Housing - Find expensive houses
print("🏠 HOUSING DATASET:")

# Step 1: Create boolean mask (array of True/False)
expensive_mask = y_housing > 5.0  # True where price > $500K, False otherwise
print(f"Boolean mask (first 10): {expensive_mask[:10]}")
print(f"  Type: {expensive_mask.dtype}")  # dtype=bool
print(f"  Shape: {expensive_mask.shape}")  # Same shape as y_housing

# Step 2: Count how many True values
num_expensive = expensive_mask.sum()  # sum() treats True=1, False=0
print(f"Number of expensive houses (>${500000}): {num_expensive:,} out of {len(y_housing):,}")
print(f"Percentage: {num_expensive / len(y_housing) * 100:.2f}%")

# Step 3: Use mask to filter data
expensive_houses = X_housing[expensive_mask]  # Only rows where mask=True
expensive_prices = y_housing[expensive_mask]
print(f"Expensive houses shape: {expensive_houses.shape}")
print(f"First 3 expensive houses (first 3 features):\n{expensive_houses[:3, :3]}")
print(f"Their prices: ${expensive_prices[:3] * 100000}")

# Multiple conditions with & (AND) and | (OR)
# Find houses with high income AND expensive price
high_income = X_housing[:, 0] > 6.0  # Median income > 6.0
expensive_high_income = expensive_mask & high_income  # Both conditions must be True
print(f"\nHouses with high income AND expensive price: {expensive_high_income.sum():,}")

# Find houses that are EITHER old OR expensive
old_houses = X_housing[:, 1] > 40  # House age > 40 years
old_or_expensive = old_houses | expensive_mask  # Either condition can be True
print(f"Houses that are old OR expensive: {old_or_expensive.sum():,}")

# Dataset 2: Iris - Find large flowers
print("\n🌸 IRIS DATASET:")

# Find flowers with large petals (length > 5cm)
large_petal_mask = X_iris[:, 2] > 5.0  # Column 2 = Petal Length
large_petal_flowers = X_iris[large_petal_mask]
print(f"Flowers with petal length > 5cm: {large_petal_mask.sum()} out of 150")
print(f"First 3 large-petal flowers:\n{large_petal_flowers[:3]}")

# Find Setosa flowers (species = 0)
setosa_mask = y_iris == 0  # Equal to 0
setosa_count = setosa_mask.sum()
print(f"\nSetosa flowers: {setosa_count}")
print(f"Average sepal length of Setosa: {X_iris[setosa_mask, 0].mean():.2f} cm")

# Find flowers that are NOT Setosa (species != 0)
not_setosa_mask = y_iris != 0  # Not equal to 0
not_setosa_count = not_setosa_mask.sum()
print(f"Non-Setosa flowers: {not_setosa_count}")

# Complex condition: Large petals AND Virginica species
virginica_mask = y_iris == 2  # Virginica = class 2
large_virginica = large_petal_mask & virginica_mask
print(f"Large Virginica flowers: {large_virginica.sum()}")

# Dataset 3: Wine - Find high-quality wines
print("\n🍷 WINE DATASET:")

# Find wines with high alcohol content (>14%)
high_alcohol_mask = X_wine[:, 0] > 14.0
high_alcohol_wines = X_wine[high_alcohol_mask]
print(f"Wines with alcohol > 14%: {high_alcohol_mask.sum()} out of {len(X_wine)}")
print(f"Average phenols in high-alcohol wines: {high_alcohol_wines[:, 6].mean():.2f}")

# Find wines of class 0 (first wine type)
class_0_mask = y_wine == 0
class_0_wines = X_wine[class_0_mask]
print(f"\nClass 0 wines: {class_0_mask.sum()}")
print(f"Average alcohol in class 0: {class_0_wines[:, 0].mean():.2f}%")

# Find premium wines: High alcohol AND High phenols
high_phenols_mask = X_wine[:, 6] > 3.0  # Column 6 = Total Phenols
premium_mask = high_alcohol_mask & high_phenols_mask
print(f"Premium wines (high alcohol AND phenols): {premium_mask.sum()}")

# ============================================================================
# PART 4: FANCY INDEXING - Using Arrays of Indices
# ============================================================================
print("\n\n4️⃣ FANCY INDEXING - Select Specific Indices")
print("-" * 70)
print("Use case: Select non-consecutive samples (e.g., indices [0, 5, 10, 50])")

# Dataset 1: Housing - Select specific houses by index
print("🏠 HOUSING DATASET:")
selected_indices = [0, 100, 500, 1000, 5000, 10000]  # Random houses
selected_houses = X_housing[selected_indices]  # Select rows at these indices
selected_prices = y_housing[selected_indices]
print(f"Selected {len(selected_indices)} houses at indices: {selected_indices}")
print(f"Their shapes: {selected_houses.shape}")
print(f"Their prices: ${selected_prices * 100000}")

# Dataset 2: Iris - Select specific flowers
print("\n🌸 IRIS DATASET:")
flower_indices = [0, 50, 100]  # First flower of each species
selected_flowers = X_iris[flower_indices]
selected_species = y_iris[flower_indices]
print(f"Selected flowers at indices: {flower_indices}")
print(f"Selected flowers:\n{selected_flowers}")
print(f"Species: {[iris_targets[s] for s in selected_species]}")

# Dataset 3: Wine - Select random wine samples
print("\n🍷 WINE DATASET:")
wine_indices = np.array([10, 20, 30, 40, 50])  # Can use NumPy array for indices
selected_wines = X_wine[wine_indices]
selected_classes = y_wine[wine_indices]
print(f"Selected wines at indices: {wine_indices}")
print(f"Selected wines shape: {selected_wines.shape}")
print(f"Their classes: {selected_classes}")
print(f"Class names: {[wine_targets[c] for c in selected_classes]}")

# ============================================================================
# IMPORTANT: Views vs Copies
# ============================================================================
print("\n\n⚠️ CRITICAL CONCEPT: VIEWS vs COPIES")
print("-" * 70)

# Slicing creates a VIEW (changes affect original!)
sample = X_housing[:5, :2].copy()  # Make a copy to not modify original
view = X_housing[:5, :2]  # This is a VIEW, not a copy!

# Demonstrate view behavior
print("Original data (first house, first feature): {:.4f}".format(X_housing[0, 0]))

# Modify the view
view_backup = view.copy()  # Save original values
view[0, 0] = 999.0  # Change first element

print(f"After modifying view: {X_housing[0, 0]:.4f}")  # Original changed too!
print("⚠️ Slicing creates VIEWS - original data is modified!")

# Restore original value
X_housing[0, 0] = view_backup[0, 0]
print(f"Restored to: {X_housing[0, 0]:.4f}")

# Fancy indexing creates a COPY (changes DON'T affect original)
indices = [0, 1, 2]
fancy_copy = X_housing[indices]  # This is a COPY
fancy_copy[0, 0] = 999.0  # Modify the copy
print(f"\nOriginal after fancy indexing change: {X_housing[0, 0]:.4f}")  # Not changed!
print("✅ Fancy indexing creates COPIES - safe to modify!")

# Best practice: Use .copy() when you want independent array
independent_array = X_housing[:10].copy()  # Explicit copy
print("\n💡 Best practice: Use .copy() when you need independent array")

print("\n" + "=" * 70)
print("✅ INDEXING MASTERED: Basic, Slicing, Boolean, Fancy!")
print("=" * 70)



3️⃣ BOOLEAN INDEXING - Filtering with True/False Masks
----------------------------------------------------------------------
Use case: Find data matching conditions (>, <, ==, etc.)
🏠 HOUSING DATASET:
Boolean mask (first 10): [False False False False False False False False False False]
  Type: bool
  Shape: (20640,)
Number of expensive houses (>$500000): 965 out of 20,640
Percentage: 4.68%
Expensive houses shape: (965, 8)
First 3 expensive houses (first 3 features):
[[ 1.2434     52.          2.92941176]
 [ 1.1696     52.          2.436     ]
 [ 7.8521     52.          7.79439252]]
Their prices: $[500001. 500001. 500001.]

Houses with high income AND expensive price: 658
Houses that are old OR expensive: 4,537

🌸 IRIS DATASET:
Flowers with petal length > 5cm: 42 out of 150
First 3 large-petal flowers:
[[6.  2.7 5.1 1.6]
 [6.3 3.3 6.  2.5]
 [5.8 2.7 5.1 1.9]]

Setosa flowers: 50
Average sepal length of Setosa: 5.01 cm
Non-Setosa flowers: 100
Large Virginica flowers: 41

🍷 WINE DATAS

---
<a id="projects"></a>
## 🚀 Chapter Completed! Now Practice with Projects

### 🎉 Congratulations! You've Mastered NumPy Foundations!

You've learned:
✅ What NumPy is and why it's 50-100x faster than Python lists
✅ How to create arrays using 10+ different methods
✅ How to load and explore 3 different real-world datasets
✅ Indexing: Basic, slicing, boolean, and fancy indexing
✅ The difference between views and copies (critical!)

### 📊 Practice Summary:
- **20,640 housing samples** analyzed
- **150 iris flowers** classified  
- **178 wine samples** evaluated
- **Every concept** applied to **all 3 datasets**

---

## 📝 Next Steps: Apply Your Skills in Projects!

Now it's time to apply what you learned in **real projects**. Complete these projects to solidify your NumPy skills:

### 🎯 Recommended Projects (in order):

#### 1. **Project 01: Data Cleaning & Exploration** ⭐ Beginner
**What you'll do:**
- Load real datasets (Titanic, Housing)
- Handle missing values using NumPy techniques
- Perform statistical analysis
- Create derived features

**Skills practiced:**
- Array creation and manipulation
- Boolean indexing for filtering
- Statistical functions (mean, std, percentile)
- Data type conversions

**Time:** 2-3 hours  
**Link:** [Open Project 01](../projects/Project_01_DataCleaning.md)

---

#### 2. **Project 02: Visualization & EDA** ⭐⭐ Beginner-Intermediate
**What you'll do:**
- Use NumPy arrays with Matplotlib
- Create statistical visualizations
- Analyze correlations
- Build dashboards

**Skills practiced:**
- Array operations for plotting
- Statistical analysis
- Broadcasting and vectorization
- Multi-dimensional arrays

**Time:** 3-4 hours  
**Link:** [Open Project 02](../projects/Project_02_Visualization.md)

---

#### 3. **Project 05: Clustering & PCA** ⭐⭐ Intermediate
**What you'll do:**
- Dimensionality reduction with NumPy
- K-Means clustering implementation
- Principal Component Analysis
- Distance calculations

**Skills practiced:**
- Linear algebra operations
- Matrix multiplication
- Eigenvalues and eigenvectors
- Advanced indexing

**Time:** 3 hours  
**Link:** [Open Project 05](../projects/Project_05_Clustering_PCA.md)

---

### 💡 Why Do Projects?

**Reading ≠ Understanding. Practice = Mastery.**

- **Retention**: You remember 10% of what you read, 90% of what you practice
- **Confidence**: Projects prove you can solve real problems
- **Portfolio**: Showcase your skills to employers
- **Debugging**: Learn by fixing errors (most valuable skill!)

---

## 📚 Continue Learning: Next Chapter

Once you complete 1-2 projects, move to the next chapter:

### ➡️ **Chapter 02: pandas - Data Manipulation**
Learn to work with tabular data, DataFrames, and advanced data operations.

**Link:** [Open Chapter 02](02_Pandas_DataManipulation.ipynb)

---

## 🔗 Quick Navigation

| Resource | Link |
|----------|------|
| **Main Index** | [index.md](../index.md) |
| **Start Guide** | [START_HERE.md](../START_HERE.md) |
| **All Projects** | [projects/README.md](../projects/README.md) |
| **Chapter 02** | [02_Pandas_DataManipulation.ipynb](02_Pandas_DataManipulation.ipynb) |
| **Chapter 03** | [03_Matplotlib_Visualization.ipynb](03_Matplotlib_Visualization.ipynb) |
| **Chapter 04** | [04_ScikitLearn_MachineLearning.ipynb](04_ScikitLearn_MachineLearning.ipynb) |

---

## 📖 Additional Resources

- **NumPy Documentation**: [https://numpy.org/doc/stable/](https://numpy.org/doc/stable/)
- **NumPy Cheat Sheet**: [Download PDF](https://numpy.org/doc/stable/_downloads/numpy-user-guide.pdf)
- **Video Tutorial**: [https://youtu.be/9DhZ-JCWvDw](https://youtu.be/9DhZ-JCWvDw)
- **Practice Exercises**: [NumPy Exercises](https://www.w3resource.com/python-exercises/numpy/)

---

**🎓 You're now ready to build real data science projects with NumPy!**

**Remember:** 
- Every concept was applied to **3 datasets** 
- Every line of code has **detailed comments**
- Every explanation is **focused and accurate**

**Next action:** Open **Project 01** and start coding! 💻